# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# CENTRAL COMMAND MAP TEMPLATES
# CC Shuttle Dock - This is where we drop the players off after the round ends
[templates.centcom_shuttle_dock]
map_files = ["centcom_shuttle_dock.dmm"]
directory = "_maps/skyrat/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [186, 70, 1]
trait_name = "CentCom"

# CC Ferry Dock - Admin Shuttle
[templates.centcom_ferry_dock]
map_files = ["centcom_ferry_dock.dmm"]
directory = "_maps/skyrat/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [128, 79, 1]
trait_name = "CentCom"

#----- Start Tannhauser Edits -----

# CC Shuttle Dock - This is so we can fit the larger Cargo shuttle added by mortisdeum
[templates.centcom_cargo_dock]
map_files = ["centcom_cargo_dock.dmm"]
directory = "_maps/tannhauser/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [152, 101, 1]
trait_name = "CentCom"

# CC Arrivals Dock - This is so we can fit the larger arrivals shuttle added by mortisdeum
[templates.centcom_arrivals_dock]
map_files = ["centcom_arrivals_dock.dmm"]
directory = "_maps/tannhauser/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [28, 198, 2]
trait_name = "CentCom"

# METASTATION MAP TEMPLATES
# Metastation Arrivals
[templates.metastaton_arrivals]
map_files = ["metastation_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [20, 107, 1]
trait_name = "Station"

# DELTASTATION MAP EDITS
# Deltastation Arrivals
[templates.deltastation_arrivals]
map_files = ["deltastation_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [126, 195, 1]
trait_name = "Station"

# ICEBOX MAP EDITS
# Icebox Arrivals
[templates.icebox_arrivals]
map_files = ["icebox_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [10, 116, 3]
trait_name = "Station"

# KILOSTATION MAP EDITS
# Kilostation Arrivals
[templates.kilostation_arrivals]
map_files = ["kilostation_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/kilostation/"
required_map = "KiloStation.dmm"
coordinates = [151, 80, 1]
trait_name = "Station"

# TRAMSTATION MAP EDITS
# Tramstation Arrivals
[templates.tramstation_arrivals]
map_files = ["tramstation_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [14, 96, 2]
trait_name = "Station"

# BLUESHIFT MAP EDITS
# BlueShift Arrivals
[templates.blueshift_arrivals]
map_files = ["blueshift_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/blueshift/"
required_map = "BlueShift_lower.dmm"
coordinates = [154, 87, 1]
trait_name = "Station"

# VOIDRAPTOR MAP EDITS
# VoidRaptor Arrivals
[templates.voidraptor_arrivals]
map_files = ["voidraptor_arrivals.dmm"]
directory = "_maps/tannhauser/automapper/templates/voidraptor/"
required_map = "VoidRaptor.dmm"
coordinates = [75, 140, 1]
trait_name = "Station"



#----- End Tannhauser Edits -----

# METASTATION MAP TEMPLATES
# Metastation Arrivals
#[templates.metastaton_arrivals]
#map_files = ["metastation_arrivals.dmm"]
#directory = "_maps/skyrat/automapper/templates/metastation/"
#required_map = "MetaStation.dmm"
#coordinates = [20, 107, 1]
#trait_name = "Station"

# Metastation Cryo
[templates.metastation_cryo]
map_files = ["metastation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [136, 181, 1]
trait_name = "Station"

# Metastation Barber
[templates.metastation_barber]
map_files = ["metastation_barber.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [101, 116, 1]
trait_name = "Station"

# Metastation Armory
[templates.metastation_armory]
map_files = ["metastation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [101, 170, 1]
trait_name = "Station"

# Metastation NTR Office
[templates.metastation_ntrep_office]
map_files = ["metastation_ntrep_office.dmm"]
directory = "_maps/skyrat/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [56, 119, 1]
trait_name = "Station"

# DELTASTATION MAP EDITS

# Deltastation Arrivals
#[templates.deltastation_arrivals]
#map_files = ["deltastation_arrivals.dmm"]
#directory = "_maps/skyrat/automapper/templates/deltastation/"
#required_map = "DeltaStation2.dmm"
#coordinates = [126, 195, 1]
#trait_name = "Station"

# Deltastation Cryo
[templates.deltastation_cryo]
map_files = ["deltastation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [216, 93, 1]
trait_name = "Station"

# Deltastation Armorys
[templates.deltastation_armory]
map_files = ["deltastation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [207, 127, 1]
trait_name = "Station"

# Deltastation Barber
[templates.deltastation_barber]
map_files = ["deltastation_barber.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [121, 124, 1]
trait_name = "Station"

# Deltastation NTR Office
[templates.deltastation_ntrep_office]
map_files = ["deltastation_ntrep_office.dmm"]
directory = "_maps/skyrat/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [123, 143, 1]
trait_name = "Station"

# ICEBOX MAP EDITS
# Icebox Arrivals
#[templates.icebox_arrivals]
#map_files = ["icebox_arrivals.dmm"]
#directory = "_maps/skyrat/automapper/templates/icebox/"
#required_map = "IceBoxStation.dmm"
#coordinates = [10, 116, 3]
#trait_name = "Station"

# Icebox Armory Top
[templates.icebox_armory_top]
map_files = ["icebox_armory_top.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [100, 177, 3]
trait_name = "Station"

# Icebox Armory Middle
[templates.icebox_armory_middle]
map_files = ["icebox_armory_middle.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [100, 177, 2]
trait_name = "Station"

# Icebox Cryo
[templates.icebox_cryo]
map_files = ["icebox_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [116, 142, 3]
trait_name = "Station"

# Icebox Barber
[templates.icebox_barber]
map_files = ["icebox_barber.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [87, 128, 3]
trait_name = "Station"

# Icebox NTR Office
[templates.icebox_ntrep_office]
map_files = ["icebox_ntrep_office.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [92, 118, 2]
trait_name = "Station"

# Icebox HoP Maint
[templates.icebox_hop_maint]
map_files = ["icebox_hop_maint.dmm"]
directory = "_maps/skyrat/automapper/templates/icebox/"
required_map = "IceBoxStation.dmm"
coordinates = [98, 123, 3]
trait_name = "Station"

# KILOSTATION MAP EDITS
# Kilostation Arrivals
#[templates.kilostation_arrivals]
#map_files = ["kilostation_arrivals.dmm"]
#directory = "_maps/skyrat/automapper/templates/kilostation/"
#required_map = "KiloStation.dmm"
#coordinates = [151, 80, 1]
#trait_name = "Station"

# Kilostation ERT Bay and Barber
[templates.kilostation_ert_bay]
map_files = ["kilostation_ert_bay.dmm"]
directory = "_maps/skyrat/automapper/templates/kilostation/"
required_map = "KiloStation.dmm"
coordinates = [77, 151, 1]
trait_name = "Station"

# Kilostation Cryo
[templates.kilostation_cryo]
map_files = ["kilostation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/kilostation/"
required_map = "KiloStation.dmm"
coordinates = [59, 118, 1]
trait_name = "Station"

# Kilostation Armory
[templates.kilostation_armory]
map_files = ["kilostation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/kilostation/"
required_map = "KiloStation.dmm"
coordinates = [80, 77, 1]
trait_name = "Station"

# TRAMSTATION MAP EDITS
# Tramstation Arrivals
#[templates.tramstation_arrivals]
#map_files = ["tramstation_arrivals.dmm"]
#directory = "_maps/skyrat/automapper/templates/tramstation/"
#required_map = "tramstation.dmm"
#coordinates = [14, 96, 2]
#trait_name = "Station"

# Tramstation Armory
[templates.tramstation_armory]
map_files = ["tramstation_armory.dmm"]
directory = "_maps/skyrat/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [73, 161, 2]
trait_name = "Station"

# Tramstation Barber
[templates.tramstation_barber]
map_files = ["tramstation_barber.dmm"]
directory = "_maps/skyrat/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [117, 151, 1]
trait_name = "Station"

# Tramstation Barber Cover
[templates.tramstation_barber_cover]
map_files = ["tramstation_barber_cover.dmm"]
directory = "_maps/skyrat/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [118, 164, 2]
trait_name = "Station"

# Tramstation Cryo
[templates.tramstation_cryo]
map_files = ["tramstation_cryo.dmm"]
directory = "_maps/skyrat/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [74, 102, 2]
trait_name = "Station"

# Tramstation NTR Office
[templates.tramstation_ntrep_office]
map_files = ["tramstation_ntrep_office.dmm"]
directory = "_maps/skyrat/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [129, 149, 1]
trait_name = "Station"

# Tramstation NTR Office Cover - Due to how this is placed, the above layer doesn't make a ceiling
[templates.tramstation_ntrep_office_cover]
map_files = ["tramstation_ntrep_office_cover.dmm"]
directory = "_maps/skyrat/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [135, 162, 2]
trait_name = "Station"


# Tannhauser Gate Overrides go below this line

# ICEBOX MAP EDITS

# Manaforge Jade Dragon
[templates.manaforge_jade]
map_files = ["jade_dragon.dmm"]
directory = "_maps/tannhauser/automapper/manaforge/"
required_map = "IceBoxStation.dmm"
coordinates = [156, 62, 3]
trait_name = "Station"

# Manaforge Warpstone Laboratry
[templates.warpstone_lab]
map_files = ["warpstone_lab.dmm"]
directory = "_maps/tannhauser/automapper/manaforge/"
required_map = "IceBoxStation.dmm"
coordinates = [184, 99, 2]
trait_name = "Station"

# Manaforge Warpstone Laboratry
[templates.mana_arcade]
map_files = ["arcade.dmm"]
directory = "_maps/tannhauser/automapper/manaforge/"
required_map = "IceBoxStation.dmm"
coordinates = [134, 69, 2]
trait_name = "Station"
